[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path  = "forge-cache"
solc-version = "0.8.27"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer-runs = 2000

rpc_endpoints = { mainnet = "https://eth.drpc.org", holesky = "https://rpc.ankr.com/eth_holesky" }
